# Generated by Django 3.1.2 on 2020-11-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadet',
            name='cantidad_menu',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facturadet',
            name='total_alumnos',
            field=models.FloatField(default=0),
        ),
    ]
